version: "2"

linters:
  exclusions:
    # Generated file analysis - strict means they follow the guidelines here: https://go.dev/s/generatedcode
    generated: strict
    # Log a warning if an exclusion rule is unused.
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - staticcheck
        text: "QF1008:" # this lint is not useful for tests

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    # Generated file analysis - strict means they follow the guidelines here: https://go.dev/s/generatedcode
    generated: strict
