AWSConfig:
  AccessKeyID: <YOUR AWS ACCESS KEY ID>
  SecretAccessKey: <YOUR AWS SECRET ACCESS KEY>
  Region: <YOUR AWS REGION>
  CloudFormationConfig:
    DeploymentRoleName: PantherDeploymentRole # WE RECOMMEND USING THIS VALUE
    IdentityAccountId: <ASK FOR THIS INFORMATION FROM PANTHER>
    OpsAccountId: <ASK FOR THIS INFORMATION FROM PANTHER>
  DomainCertificateConfiguration:
    PantherSubdomain: panther.yourdomain.com # THIS IS AN EXAMPLE, CHANGE IT TO YOUR DOMAIN

SnowflakeOrgConfig:
  AccountLocator: <YOUR SNOWFLAKE ACCOUNT LOCATOR> # https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-account-locator-in-a-region
  AccountRegion: <YOUR SNOWFLAKE ACCOUNT REGION> # Format this as an AWS region name - e.g. us-west-2
  OrgAdminUsername: <YOUR ORGADMIN USERNAME>
  # Path to the file containing your Snowflake OrgAdmin private key
  OrgAdminPrivateKeyPath: /path/to/your/private-key.pem

NewAccountConfig:
  AccountName: <YOUR NEW SNOWFLAKE ACCOUNT NAME> # e.g. yourcompany-panther
  AdminUsername: <YOUR NEW SNOWFLAKE ACCOUNT ADMIN USERNAME> # e.g. yourusername
  AdminPassword: 123455678-DE3C-4F67-DDDD-1234asdfasdf! # replace with a strong password
  AdminEmail: <YOUR ADMIN USER'S EMAIL>
  SnowflakeEdition: ENTERPRISE # STANDARD, BUSINESS_CRITICAL, or ENTERPRISE - we recommend ENTERPRISE for full features
  PantherEdition: ENTERPRISE # ESSENTIALS or ENTERPRISE - if this is ENTERPRISE, SnowflakeEdition must be ENTERPRISE
  PantherRegion: <YOUR PANTHER REGION> # Format this as an AWS region name - e.g. us-west-2
